// GENERATED by the workspace tooling. Do not edit.
import { deployContract, findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import type { JubjubPoint, TxData, SchnorrSignature } from './types.js';
export type * from './types.js';

type CallResult = { public: { txId: string; txHash: string; blockHeight: number } };
type Found = { callTx: Record<string, (...a: any[]) => Promise<CallResult>>; deployTxData: { public: { contractAddress: string } } };

const toTxData = (r: CallResult): TxData => ({ txId: String(r.public.txId), txHash: r.public.txHash, blockHeight: r.public.blockHeight });

/** Typed wrapper over midnight-js callTx for fungible-token-native-v3. */
export class FungibleTokenNativeV3Client {
  private constructor(private readonly found: Found) {}

  static async deploy(providers: unknown, compiledContract: unknown, args: unknown[]): Promise<FungibleTokenNativeV3Client> {
    const found = await (deployContract as any)(providers, { compiledContract, args });
    return new FungibleTokenNativeV3Client(found as Found);
  }

  static async connect(providers: unknown, compiledContract: unknown, contractAddress: string): Promise<FungibleTokenNativeV3Client> {
    const found = await (findDeployedContract as any)(providers, { compiledContract, contractAddress });
    return new FungibleTokenNativeV3Client(found as Found);
  }

  get contractAddress(): string {
    return this.found.deployTxData.public.contractAddress;
  }

  /** Calls circuit `mint`. */
  async mint(to: Uint8Array, value: bigint, pubkeys: JubjubPoint[], signatures: SchnorrSignature[]): Promise<TxData> {
    return toTxData(await this.found.callTx.mint(to, value, pubkeys, signatures));
  }

  /** Calls circuit `burn`. */
  async burn(value: bigint, pubkeys: JubjubPoint[], signatures: SchnorrSignature[]): Promise<TxData> {
    return toTxData(await this.found.callTx.burn(value, pubkeys, signatures));
  }

  /** Calls circuit `contractWithdraw`. */
  async contractWithdraw(to: Uint8Array, value: bigint, pubkeys: JubjubPoint[], signatures: SchnorrSignature[]): Promise<TxData> {
    return toTxData(await this.found.callTx.contractWithdraw(to, value, pubkeys, signatures));
  }

  /** Calls circuit `setEmergencyPauser`. */
  async setEmergencyPauser(newPauser: Uint8Array, pubkeys: JubjubPoint[], signatures: SchnorrSignature[]): Promise<TxData> {
    return toTxData(await this.found.callTx.setEmergencyPauser(newPauser, pubkeys, signatures));
  }

  /** Calls circuit `rotateSigner`. */
  async rotateSigner(oldSignerCommitment: Uint8Array, newSignerPubkey: JubjubPoint, newSignerPop: SchnorrSignature, pubkeys: JubjubPoint[], signatures: SchnorrSignature[]): Promise<TxData> {
    return toTxData(await this.found.callTx.rotateSigner(oldSignerCommitment, newSignerPubkey, newSignerPop, pubkeys, signatures));
  }

  /** Calls circuit `pause`. */
  async pause(caller: Uint8Array): Promise<TxData> {
    return toTxData(await this.found.callTx.pause(caller));
  }

  /** Calls circuit `unpause`. */
  async unpause(caller: Uint8Array): Promise<TxData> {
    return toTxData(await this.found.callTx.unpause(caller));
  }

  /** Calls circuit `deposit`. */
  async deposit(value: bigint): Promise<TxData> {
    return toTxData(await this.found.callTx.deposit(value));
  }

  /** Calls circuit `emergencyWithdraw`. */
  async emergencyWithdraw(caller: Uint8Array, value: bigint): Promise<TxData> {
    return toTxData(await this.found.callTx.emergencyWithdraw(caller, value));
  }
}
